### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by zzd1994** [WXinlong/SOLO#22]
你好，请问训练自己的数据集还要改哪些地方呢，我的数据集在训练的时候没报错，但在测试的时候报错了，还有类别名和类别数目没改没关系吗？
期待您的解答，谢谢！

**Comment by WXinlong** [comment]
@zzd1994  Can you provide your output log?

**Comment by zzd1994** [comment]
when testing,
Traceback (most recent call last):
  File "test_ins.py", line 257, in <module>
    main()
  File "test_ins.py", line 235, in main
    coco_eval(result_files, eval_types, dataset.coco)
  File "/home/jskj/Projects/SOLO-master/mmdet/core/evaluation/coco_utils.py", line 41, in coco_eval
    coco_dets = coco.loadRes(result_file)
  File "/home/jskj/.conda/envs/solov1/lib/python3.7/site-packages/pycocotools/coco.py", line 326, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

i don't know how to modify the hyperparameter for my own dataset, and the model is solo_r101_fpn_8gpu_3x

**Comment by LiXm1002** [comment]
I met same question, I have changed the `num_classes = 2` because my data has only one category. when I run inference_demo.py . It get some errors.
`/home/ubuntu/anaconda3/envs/solov1/lib/python3.6/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "demo/inference_demo.py", line 20, in <module>
    show_result_ins(img, result, model.CLASSES, score_thr=0.25, out_file="pig_out.jpg")
  File "/media/ubuntu/SSD/SOLO-master/mmdet/apis/inference.py", line 237, in show_result_ins
    seg_label = cur_result[0]
TypeError: 'NoneType' object is not subscriptable
`

**Comment by ceciliaAI** [comment]
@LiXm1002  hi I trained the model without error, but the prediction result is also error, it seems that the prediction is None, have you solved this problem?

**Comment by yfjiang1990** [comment]
I have the same problem, has someone  solved this problem?

**Comment by zzd1994** [comment]
> I have the same problem, has someone solved this problem?
@yfjiang1990 maybe you should check you own coco-format dataset or re-install mmdetection, i forgot it in detail...
