### ISSUE TITLE
What is the kernel and sigma in test_cfg?

### ISSUE THREAD

**Issue by zeal-github** [WXinlong/SOLO#51]
Hi, I am confused about some params in test config.
```
test_cfg = dict(
    nms_pre=500,
    score_thr=0.1,
    mask_thr=0.5,
    update_thr=0.05,
    kernel='gaussian',  # gaussian/linear
    sigma=2.0,
    max_per_img=100)
```
what is the update_thr, kernel, sigma mean here?
Can't I adjust NMS_threshold in the NMS operation like in maskrcnn?

**Comment by zzzzzz0407** [comment]
Hi, 'kernel' is the decay mode in Matrix NMS, it can be 'gaussian' or 'linear', i.e., two decay methods. And 'sigma' is the decay factor for 'gaussian' method. These parameters are in line with Soft NMS. Please refer to https://arxiv.org/pdf/2003.10152.pdf for more details about Matrix NMS.
Moreover, if you use the trational NMS rather than Matrix NMS (default), the NMS_threshhold (e.g. 0.5) is enough.
We will update the trational NMS as soon.
